### ISSUE TITLE
请检查配置文件是否配置了userAPI，检查本机是否联网

### ISSUE THREAD

**Issue by Leo4ML** [Jack-Laoyang/AutoXue2#15]
学习强国版本：2.19和2.20
autoxue2版本：3.4
前天和昨天都正常使用，今天早上一切正常操作，cmd窗口提示“请检查配置文件是否配置了userAPI，检查本机是否联网” 回车退出程序。
尝试过：重启电脑→彻底删除autoxue文件夹→重新解压→重新配置→同样问题出现。
网络环境：电脑网络正常，雷电模拟器网络正常
userapi状态：在配置文件中有看到userapi是有配置的
求解决

**Comment by haoxiaodao** [comment]
我今天也遇到了这个问题

**Comment by Leo4ML** [comment]
> 学习强国版本：2.19和2.20
> autoxue2版本：3.4
> 前天和昨天都正常使用，今天早上一切正常操作，cmd窗口提示“请检查配置文件是否配置了userAPI，检查本机是否联网” 回车退出程序。
> 尝试过：重启电脑→彻底删除autoxue文件夹→重新解压→重新配置→同样问题出现。
> 网络环境：电脑网络正常，雷电模拟器网络正常
> userapi状态：在配置文件中有看到userapi是有配置的
> 求解决

什么操作都没做 今天再打开又一切正常.......
