### ISSUE TITLE
一直显示检查本机是否联网的提示！重启手机电脑都不管用！肯定网是没问题的

### ISSUE THREAD

**Issue by hl198543** [Jack-Laoyang/AutoXue2#32]

**Comment by hl198543** [comment]
![Uploading image.png…]()

**Comment by hl198543** [comment]
![微信截图_20210127131409](https://user-images.githubusercontent.com/59598100/105947164-96bf7e80-60a3-11eb-8595-4d1662045ad4.png)

**Comment by hl198543** [comment]
![20210127131409](https://user-images.githubusercontent.com/59598100/105947196-a939b800-60a3-11eb-87fc-6b81a2cb215b.jpg)

**Comment by hl198543** [comment]
![20210127131409](https://user-images.githubusercontent.com/59598100/105947258-c79fb380-60a3-11eb-9484-1159d9bfe9da.jpg)

**Comment by hl198543** [comment]
![image](https://user-images.githubusercontent.com/59598100/105947292-d5edcf80-60a3-11eb-9b7d-e73a0adce10e.png)

**Comment by hl198543** [comment]
![20210127131409](https://user-images.githubusercontent.com/59598100/105947433-10576c80-60a4-11eb-9ccf-44fac54937b4.jpg)

**Comment by hl198543** [comment]
![20210127131409](https://user-images.githubusercontent.com/59598100/105947611-5d3b4300-60a4-11eb-8617-779f40eb16bb.jpg)

**Comment by Clark3333** [comment]
我也有这个问题

**Comment by wslmwps888** [comment]
大佬可有联系方式？
